### PR TITLE
Add chomp & now aliases

### PR DESCRIPTION
**Pull request by mxr**

### CODE REVIEW

**Comment by mxr** [comment]
@jmphilli what do you think of these aliases?

**Comment by jmphilli** [comment]
+1

**Comment by mxr** [comment]
Merge me please

**Comment by jmphilli** [comment]
lol can you not merge?

**Comment by jmphilli** [comment]
sorry!

**Comment by mxr** [comment]
Don't think I'm a collaborator on this glorious repo but I'll trade you for
a bagel tmrw morning

**Pull request merged**
